parameters:
    database_host: localhost
    database_username: root
    database_password: 
    database_name: violetta
    facebook_app_id: ''
    facebook_app_secret: ''
    facebook_app_host: ''
    facebook_tab_url: ''
    facebook_login_scope: 'public_profile, email, publish_actions'