Odiseo\ViolettaPromo\Model\Code:
    type: entity
    table: code
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 255
            unique: true
        createdAt:
            type: datetime
            column: created_at