Odiseo\ViolettaPromo\Model\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: created_at
        dateInit:
            type: date
            column: date_init
        step:
            type: integer
        increment:
            type: integer