Odiseo\ViolettaPromo\Model\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        dni:
            type: string
            length: 8
            unique: true
        fullname:
            type: string
            length: 140
            nullable: true
        email:
            type: string
            length: 140
            nullable: true
        phone:
            type: string
            length: 80
            nullable: true
        createdAt:
            type: datetime
            column: created_at
    oneToMany:
        participations:
            targetEntity: UserParticipation
            mappedBy: user